# Site settings
title: Wil Whiting
email: contact@wilwhiting.com
url: http://wilwhiting.com
description: "Wil Whiting crafts bespoke shirts made unique to each individual,<br/>extending to one-off couture pieces for both men and women."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Wil Whiting Ltd

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/wilwhiting/

# Build settings
markdown: kramdown
permalink: pretty
